CREATE TABLE "users"(
 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "Name" varchar(15) NOT NULL,
 "age" int,
 "password" varchar(15) NOT NULL,

);

CREATE TABLE "level"(
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(15) NOT NULL,
    
);
 
 CREATE TABLE "course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courses" varchar(15)not null
 
 );

 CREATE TABLE "teachers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teachers" varchar(15) NOT NULL,
 
 );

CREATE TABLE "video_url" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "video url" varchar(30) NOT NULL,

);

 CREATE TABLE "email"(
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(25) NOT NULL,
 
 );

CREATE TABLE "title_description" (
  "id"
  "title" varchar(20) NOT NULL,
  "description" varchar(20) NOT NULL,

);
 

 
 ALTER TABLE "courses" ADD FOREIGN KEY ('email') REFERENCES "email" ("id");
 
 ALTER TABLE "courses" ADD FOREIGN KEY ("level") REFERENCES "level" ("id");

 ALTER TABLE "cousers" ADD FOREIGN KEY ("teacher") REFERENCES "teacher" ("id");

 ALTER TABLE "coursers" ADD FOREIGN KEY ("title_description") REFERENCES "title_description" ("id");

ALTER TABLE "coursers" ADD FOREIGN KEY ("course") REFERENCES "course" ("id");

ALTER TABLE "coursers" ADD FOREIGN KEY ("video_url") REFERENCES "video_url" ("id");

INSERT INTO level (level) VALUES ('basico'), ('intermedio'), ('avanzado');

INSERT INTO roles (rol) VALUES ('student'), ('teacher'), ('admin');

INSERT INTO categories (category) VALUES ('diseño UI/UX'), ('programacion'), ('cybersecurity');

INSERT INTO users (name, , age, password) VALUES
(eliza, eliza@gmail.com, 20, 21234);
(ian, ianrosas@gmail.com, 34, 12211);
(brenda, brendra@gmail.com, 30, 33456);
(alejandra, alegrandra@gmail.com, 28, 76543);
(rafael, rafael@gmail.com, 17, 987654);
(jose, jose@gmail.com, 22, 983);
(jeremy, jeremy@gmail.com, 9876564, 18119);
(adrian, adrian@gmail.com, 20, 32132);
(franklin, franklin@gmail.com, 26, 55544);
(andrea, andrea@gmail.com, 18, 6988);
(diego, diego@gmail.com, 20, 3234);


INSERT INTO courses (email, course, level, teacher, title, video_url) VALUES
(5,	2,	2,	1,	1,	1);
(1,	1,	3,	2,	3,	2);
(10, 1,	3,	2,	3,	2);
(11, 3,	2,	3,	2,	3);
(6,	2,	2,	1,	1,	1);
(7,	1,	1,	1,	1,	1);
(8,	3,	2,	3,	2,	3);
(9,	1,	3,	2,	3,	2);


INSERT INTO courses_video (course, url) VALUES
(2, 'https://chef.com'),
(1, 'https://crafts.com'),
(3, 'https://drawing.com');

